config/routes.rb
Add::Application.routes.draw do

  root :to => "sai#add"

  get "cut/form"

  post "cut/result"

  get "serial/index"

  get 'sai/add'

  post 'sai/result'
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cut_controller.rb
class CutController < ApplicationController
  def form


  end

  def result
   @first = params[:first].to_i
  @second = params[:second].to_i
  @result = @first + @second
  end
end

app/controllers/sai_controller.rb
class SaiController < ApplicationController

def add
end

def result

	@first = params[:first].to_i
	@second = params[:second].to_i
	@result = @first + @second
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cut_helper.rb
module CutHelper
end

app/helpers/sai_helper.rb
module SaiHelper
end

app/helpers/serial_helper.rb
module SerialHelper
end

app/views/cut/form.html.erb
<%= form_tag cut_result_path do %>
  <%= number_field_tag :first %>
  +
  <%= number_field_tag :second %>
  <%= submit_tag "add" %>
<% end %>

app/views/cut/result.html.erb
<%= @first %> + <%= @second %> = <%= @result %>
<br/>
<%= link_to 'back', cut_form_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Add</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sai/add.html.erb
 <%= form_tag sai_result_path do %>
  <%= number_field_tag :first %> + <%= number_field_tag :second %>
  <%= submit_tag "sai add" %>
<% end %>

app/views/sai/result.html.erb
 




<%=  @result %>

<%= link_to "back to home", sai_add_path %>
<a href="/sai/add">Back</a>